language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
    - develop
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  - ng lint
  - npm run test
  - npm run build
after_success:
  - firebase deploy --project matrix-fe55c --token $FIREBASE_TOKEN
