language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
    - develop
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g @agm/core
  - npm install -g karma
  - npm install
script:
  - ng lint
  - ng test
  - ng build --prod --aot
after_success:
  - firebase deploy --project matrix-fe55c --token $FIREBASE_TOKEN
